using System;
using System.Collections.Generic;
using System.Linq;
using System.Windows.Input;
using PoeShared.Scaffolding;

namespace PoeShared.UI;

internal static class HotkeyMapping
{
    public static IDictionary<Key, string> KeysToInvariantName = new Dictionary<Key, string>()
    {
        {Key.None, "None"},
        {Key.Cancel, "Cancel"},
        {Key.Back, "Backspace"},
        {Key.Tab, "Tab"},
        {Key.LineFeed, "LineFeed"},
        {Key.Clear, "Clear"},
        {Key.Return, "Enter"},
        {Key.Pause, "Pause"},
        {Key.Capital, "Caps Lock"},
        {Key.KanaMode, "KanaMode"},
        {Key.JunjaMode, "JunjaMode"},
        {Key.FinalMode, "FinalMode"},
        {Key.HanjaMode, "HanjaMode"},
        {Key.Escape, "Esc"},
        {Key.ImeConvert, "ImeConvert"},
        {Key.ImeNonConvert, "ImeNonConvert"},
        {Key.ImeAccept, "ImeAccept"},
        {Key.ImeModeChange, "ImeModeChange"},
        {Key.Space, "Space"},
        {Key.PageUp, "Page Up"},
        {Key.Next, "Page Down"},
        {Key.End, "End"},
        {Key.Home, "Home"},
        {Key.Left, "Left"},
        {Key.Up, "Up"},
        {Key.Right, "Right"},
        {Key.Down, "Down"},
        {Key.Select, "Select"},
        {Key.Print, "Print"},
        {Key.Execute, "Execute"},
        {Key.Snapshot, "Sys Req"},
        {Key.Insert, "Insert"},
        {Key.Delete, "Delete"},
        {Key.Help, "Help"},
        {Key.D0, "0"},
        {Key.D1, "1"},
        {Key.D2, "2"},
        {Key.D3, "3"},
        {Key.D4, "4"},
        {Key.D5, "5"},
        {Key.D6, "6"},
        {Key.D7, "7"},
        {Key.D8, "8"},
        {Key.D9, "9"},
        {Key.A, "A"},
        {Key.B, "B"},
        {Key.C, "C"},
        {Key.D, "D"},
        {Key.E, "E"},
        {Key.F, "F"},
        {Key.G, "G"},
        {Key.H, "H"},
        {Key.I, "I"},
        {Key.J, "J"},
        {Key.K, "K"},
        {Key.L, "L"},
        {Key.M, "M"},
        {Key.N, "N"},
        {Key.O, "O"},
        {Key.P, "P"},
        {Key.Q, "Q"},
        {Key.R, "R"},
        {Key.S, "S"},
        {Key.T, "T"},
        {Key.U, "U"},
        {Key.V, "V"},
        {Key.W, "W"},
        {Key.X, "X"},
        {Key.Y, "Y"},
        {Key.Z, "Z"},
        {Key.LWin, "LWin"},
        {Key.RWin, "RWin"},
        {Key.Apps, "Apps"},
        {Key.Sleep, "Sleep"},
        {Key.NumPad0, "Num 0"},
        {Key.NumPad1, "Num 1"},
        {Key.NumPad2, "Num 2"},
        {Key.NumPad3, "Num 3"},
        {Key.NumPad4, "Num 4"},
        {Key.NumPad5, "Num 5"},
        {Key.NumPad6, "Num 6"},
        {Key.NumPad7, "Num 7"},
        {Key.NumPad8, "Num 8"},
        {Key.NumPad9, "Num 9"},
        {Key.Multiply, "Num *"},
        {Key.Add, "Num +"},
        {Key.Separator, "Separator"},
        {Key.Subtract, "Num -"},
        {Key.Decimal, "Num Del"},
        {Key.Divide, "/"},
        {Key.F1, "F1"},
        {Key.F2, "F2"},
        {Key.F3, "F3"},
        {Key.F4, "F4"},
        {Key.F5, "F5"},
        {Key.F6, "F6"},
        {Key.F7, "F7"},
        {Key.F8, "F8"},
        {Key.F9, "F9"},
        {Key.F10, "F10"},
        {Key.F11, "F11"},
        {Key.F12, "F12"},
        {Key.F13, "F13"},
        {Key.F14, "F14"},
        {Key.F15, "F15"},
        {Key.F16, "F16"},
        {Key.F17, "F17"},
        {Key.F18, "F18"},
        {Key.F19, "F19"},
        {Key.F20, "F20"},
        {Key.F21, "F21"},
        {Key.F22, "F22"},
        {Key.F23, "F23"},
        {Key.F24, "F24"},
        {Key.NumLock, "Num Lock"},
        {Key.Scroll, "Scroll Lock"},
        {Key.LeftShift, "Shift"},
        {Key.RightShift, "Right Shift"},
        {Key.LeftCtrl, "LeftCtrl"},
        {Key.RightCtrl, "RightCtrl"},
        {Key.LeftAlt, "LeftAlt"},
        {Key.RightAlt, "RightAlt"},
        {Key.BrowserBack, "BrowserBack"},
        {Key.BrowserForward, "BrowserForward"},
        {Key.BrowserRefresh, "BrowserRefresh"},
        {Key.BrowserStop, "BrowserStop"},
        {Key.BrowserSearch, "BrowserSearch"},
        {Key.BrowserFavorites, "BrowserFavorites"},
        {Key.BrowserHome, "BrowserHome"},
        {Key.VolumeMute, "VolumeMute"},
        {Key.VolumeDown, "VolumeDown"},
        {Key.VolumeUp, "VolumeUp"},
        {Key.MediaNextTrack, "MediaNextTrack"},
        {Key.MediaPreviousTrack, "MediaPreviousTrack"},
        {Key.MediaStop, "MediaStop"},
        {Key.MediaPlayPause, "MediaPlayPause"},
        {Key.LaunchMail, "LaunchMail"},
        {Key.SelectMedia, "SelectMedia"},
        {Key.LaunchApplication1, "LaunchApplication1"},
        {Key.LaunchApplication2, "LaunchApplication2"},
        {Key.Oem1, "Oem1"},
        {Key.OemPlus, "+"},
        {Key.OemComma, "OemComma"},
        {Key.OemMinus, "-"},
        {Key.OemPeriod, "OemPeriod"},
        {Key.OemQuestion, "OemQuestion"},
        {Key.Oem3, "`"},
        {Key.AbntC1, "AbntC1"},
        {Key.AbntC2, "AbntC2"},
        {Key.OemOpenBrackets, "OemOpenBrackets"},
        {Key.Oem5, "Oem5"},
        {Key.Oem6, "Oem6"},
        {Key.OemQuotes, "OemQuotes"},
        {Key.Oem8, "Oem8"},
        {Key.OemBackslash, "OemBackslash"},
        {Key.ImeProcessed, "ImeProcessed"},
        {Key.System, "System"},
        {Key.OemAttn, "OemAttn"},
        {Key.OemFinish, "OemFinish"},
        {Key.OemCopy, "OemCopy"},
        {Key.DbeSbcsChar, "DbeSbcsChar"},
        {Key.OemEnlw, "OemEnlw"},
        {Key.OemBackTab, "OemBackTab"},
        {Key.DbeNoRoman, "DbeNoRoman"},
        {Key.DbeEnterWordRegisterMode, "DbeEnterWordRegisterMode"},
        {Key.DbeEnterImeConfigureMode, "DbeEnterImeConfigureMode"},
        {Key.EraseEof, "EraseEof"},
        {Key.Play, "Play"},
        {Key.DbeNoCodeInput, "DbeNoCodeInput"},
        {Key.NoName, "NoName"},
        {Key.Pa1, "Pa1"},
        {Key.OemClear, "OemClear"},
        {Key.DeadCharProcessed, "DeadCharProcessed"},
    };

    public static readonly IDictionary<string, Key> InvariantNameToKey = KeysToInvariantName.ToDictionary(x => x.Value, x => x.Key, StringComparer.InvariantCultureIgnoreCase);

}