namespace PoeShared.Common
{
    public enum PoeCurrencyType
    {
        ScrollOfWisdom,
        PortalScroll,
        ArmourerSScrap,
        BlacksmithSWhetstone,
        GlassblowerSBauble,
        CartographerSChisel,
        GemcutterSPrism,
        JewellerSOrb,
        ChromaticOrb,
        OrbOfFusing,
        OrbOfTransmutation,
        OrbOfChance,
        OrbOfAlchemy,
        RegalOrb,
        OrbOfAugmentation,
        ExaltedOrb,
        OrbOfAlteration,
        ChaosOrb,
        BlessedOrb,
        DivineOrb,
        OrbOfScouring,
        MirrorOfKalandra,
        EternalOrb,
        OrbOfRegret,
        VaalOrb,
        ScrollFragment,
        TransmutationShard,
        AlterationShard,
        AlchemyShard
    }
}